Resources:
  StoreInputValue:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "{{ environment.continent }} {{ environment.stage}}"

Outputs:
  Continent:
    Value: "{{ environment.continent }}"
  Stage:
    Value: "{{ environment.stage }}"
